$('.slider').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1.2
        },
        600:{
            items:3
        },
        1025:{
            items:5
        }
    }
})