$('.slider').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1.2
        },
        600:{
            items:2.5
        },
        1000:{
            items:3.5
        }
    }
})